[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dns-manager"
dynamic = ["version"]
authors = [
  { name="fangwentong", email="fangwentong2012@gmail.com" },
]
license = "MIT"
requires-python = ">=3.7"
dependencies = [
    "PyNamecheap==0.0.3",
    "aliyun-python-sdk-alidns==2.0.6",
    "cloudflare==2.8.15",
    "PyYAML==6.0.1"
]

[project.scripts]
dns-manager = "dns_manager.dns_cli:main"

[tool.setuptools]
packages = ["dns_manager"]
package-dir = {"dns_manager" = "src"}

[tool.setuptools.dynamic]
version = {attr = "dns_manager.__version__"}
